blueprint:
  name: Motion Activated Lights with Phasing Effect
  description: Turn on lights with phasing effect when motion is detected and turn off after a specified duration.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: The binary sensor that detects motion.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    lights:
      name: Lights
      description: Lights to be turned on with phasing effect.
      selector:
        target:
          entity:
            domain: light
    phasing_duration:
      name: Phasing Duration
      description: Duration of the phasing effect (in seconds).
      default: 30
      selector:
        number:
          min: 1
          max: 600
          unit_of_measurement: seconds
    light_duration:
      name: Light Duration
      description: Duration for which the lights should remain on after motion is detected (in seconds).
      default: 60
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
action:
  - alias: "Motion Activated Lights with Phasing Effect"
    variables:
      brightness_steps: 10
      phasing_duration: !input phasing_duration
      light_duration: !input light_duration
    choose:
      - conditions:
          condition: trigger
          id: "motion_detected"
        sequence:
          - service: light.turn_on
            target: !input lights
            data:
              brightness_pct: 0
          - repeat:
              count: "{{ brightness_steps }}"
              sequence:
                - delay: "{{ phasing_duration / brightness_steps }}"
                - service: light.turn_on
                  target: !input lights
                  data:
                    brightness_pct: "{{ ((100 / brightness_steps) * repeat.index) | round(0) }}"
          - delay: "{{ light_duration }}"
          - service: light.turn_off
            target: !input lights
mode: restart
