blueprint:
  name: Motion-activated Light with Smooth Phasing Effect and Auto-Off
  description: Turn on lights with a smooth phasing effect when motion is detected and turn off after a specified duration.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: The motion sensor that triggers the light.
      selector:
        entity:
          domain: binary_sensor
    light_entity:
      name: Light Entity
      description: The light to be controlled.
      selector:
        entity:
          domain: light

mode: single
trigger:
  platform: state
  entity_id: !input 'motion_sensor'
  to: "on"
action:
  - variables:
      light_name: "{{ state_attr(input.light_entity, 'friendly_name') }}"
  - service: light.turn_on
    target:
      entity_id: !input 'light_entity'
    data:
      brightness_pct: 1
  - repeat:
      count: 5
      sequence:
        - delay: "00:00:00.04"  # Adjusted delay for 0.2 seconds total (5 steps)
        - service: light.turn_on
          target:
            entity_id: !input 'light_entity'
          data:
            brightness_pct: >
              {{ (repeat.index * 20) + 1 }}
  - delay: "00:00:10"  # Delay before turning off
  - repeat:
      count: 5
      sequence:
        - delay: "00:00:00.04"  # Adjusted delay for 0.2 seconds total (5 steps)
        - service: light.turn_on
          target:
            entity_id: !input 'light_entity'
          data:
            brightness_pct: >
              {{ 100 - (repeat.index * 20) }}
  - service: light.turn_off
    target:
      entity_id: !input 'light_entity'

automation:
  alias: "Motion Hallway Light - {{ light_name }}"
  description: "Turn on hallway light with a smooth phasing effect when motion is detected and turn off after a specified duration."
  use_blueprint:
    path: https://github.com/Juugonomics/hass/edit/main/blueprint1.yaml
