blueprint:
  name: Motion-activated Light with Phasing Effect
  description: "Turn on lights with phasing effect when motion is detected and turn off after a specified duration."
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      description: "The binary sensor that detects motion."
      selector:
        entity:
          domain: binary_sensor
    light_target:
      name: Light Target
      description: "The light to control."
      selector:
        entity:
          domain: light
    duration:
      name: Light Duration
      description: "The duration in seconds to keep the light on after motion is detected."
      default: 30
      selector:
        number:
          min: 0
          max: 600
          unit_of_measurement: seconds

trigger:
  platform: state
  entity_id: !input motion_entity
  to: "on"

action:
  - service: light.turn_on
    target: !input light_target
    data:
      brightness_pct: 1
  - repeat:
      count: 15  # Adjusted number of steps
      sequence:
        - delay: "00:00:00.033"  # Adjust delay time for smoother effect
        - service: light.turn_on
          target: !input light_target
          data:
            brightness_pct: "{{ (repeat.index * 6.67) + 1 }}"
  - delay: "00:00:{{ states('input_number.light_duration') | int }}"
  - service: light.turn_on
    target: !input light_target
    data:
      brightness_pct: 100
  - service: light.turn_off
    target: !input light_target
